### ISSUE TITLE
EF Core 8.0 support

### ISSUE THREAD

**Issue by asleire** [xo-energy/XO.EntityFrameworkCore#4]
Hi,

Are there any plans to update this to support EF Core 8.0?

It was my understanding that custom JSON serialization options would be available in EF core 8.0, but after digging around I can't find any option for it. Even if EF's new `ToJson` functionality supported custom options, `ToJson` only works on navigation properties which doesn't allow for interfaces or custom column names, making it incompatible with existing EF Core 7 applications with certain JSON options

**Comment by wjrogers** [comment]
Thanks for reaching out. I'll take a look and see whether the APIs I'm using have changed in EF Core 8.0.

**Comment by t-ashraf** [comment]
Any update on .Net 8.0 Support?

**Comment by wjrogers** [comment]
@t-ashraf @asleire I have opened a pull request (#5) that updates the project to .NET, EF Core, and Npgsql 8.0. Is either of you able to confirm that it works for you?

**Comment by wjrogers** [comment]
@asleire I pushed a fix for that bug. Thank you for reporting it!

**Comment by pietrzak-chapsvision** [comment]
Hi @wjrogers, I built your PR and referenced it in my .NET 8 project. I can confirm that it runs as expected and without errors.

However, we have encountered the following warning since this morning:
"Package 'Npgsql' 8.0.2 has a known high-severity vulnerability."

Is it possible to upgrade the package to 8.0.3 before and complete the PR?

Thank you!

**Comment by wjrogers** [comment]
Thanks, @pietrzak-chapsvision. I will update the dependency and do a release. You can always fix vulnerable dependencies yourself by referencing a newer version directly in your project.

**Comment by t-ashraf** [comment]
Thank you @wjrogers - I can confirm that the new version fixes the issue that I was having after upgrading to .Net 8.0!

👍

**Comment by t-ashraf** [comment]
Thank you @asleire and @pietrzak-chapsvision for your contributions as well.
