### ISSUE TITLE
Empty/default options breaks JSON as string serialization

### ISSUE THREAD

**Issue by pil0t** [xo-energy/XO.EntityFrameworkCore#6]
Example code:

```csharp
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp1;

class Program
{
    static void Main(string[] args)
    {
        using (var db = new MyDbContext())
        {
            db.Database.EnsureDeleted();
            db.Database.EnsureCreated();

            db.MyEntities.Add(new MyEntity
            {
                Name = "Entity 1",
                JsonData = "{\"key\": \"value\"}"
            });

            db.SaveChanges();
        }
    }
}

public class MyDbContext : DbContext
{
    public DbSet<MyEntity> MyEntities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseNpgsql("Host=localhost;Database=efcore3;Username=postgres;Password=mysecretpassword");
        // If this line present - JsonData will be serialized as string: "{\"key\": \"value\"}"
        // If comment, it will be json: {"key": "value"}
        optionsBuilder.UseNpgsqlJsonSerializerOptions(new());
    }
}

public class MyEntity
{
    public int Id { get; set; }
    public string Name { get; set; }

    [Column(TypeName = "jsonb")]
    public string JsonData { get; set; }
}


```

**Comment by wjrogers** [comment]
Passing default options like in `UseNpgsqlJsonSerializerOptions(new())`[^1] configures all `json` and `jsonb` columns to use [JsonSerializerValueConverter](https://github.com/xo-energy/XO.EntityFrameworkCore/blob/4a4242d6da73b31a5cb3f64aaf130236b0a09b12/XO.EntityFrameworkCore.NpgsqlJsonSerializerOptions/JsonSerializerValueConverter.cs). The converter simply calls `JsonSerializer.Serialize` on the property value. When the value is a string, you get an escaped JSON string. Assuming that's not what you want, you have two options:

1. If you want to store all your JSON as already-serialized strings verbatim, don't use this library.
2. If you want to use this library for some other reason not included in your example — _without_ affecting `MyEntity.JsonData` — don't pass default options to `UseNpgsqlJsonSerializerOptions`. Instead, follow the example in README step 3 to configure mapping of individual columns.

[^1]: Don't do this, by the way, it will [break `ServiceProvider` re-use](https://github.com/xo-energy/XO.EntityFrameworkCore/issues/2#issuecomment-1563113040). If you're going to pass default options, create _one_ instance of `JsonSerializerOptions` and pass that same instance every time.
